// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAB-Mcf4yuaIzEZovjuTZ4HzKe4sAgnSY',
    appId: '1:830688983522:web:59dab948d541cb7c4121bb',
    messagingSenderId: '830688983522',
    projectId: 'smart-campus-d063f',
    authDomain: 'smart-campus-d063f.firebaseapp.com',
    storageBucket: 'smart-campus-d063f.firebasestorage.app',
    measurementId: 'G-TGENZB678P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAB-Mcf4yuaIzEZovjuTZ4HzKe4sAgnSY',
    appId: '1:830688983522:android:59dab948d541cb7c4121bb',
    messagingSenderId: '830688983522',
    projectId: 'smart-campus-d063f',
    storageBucket: 'smart-campus-d063f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAB-Mcf4yuaIzEZovjuTZ4HzKe4sAgnSY',
    appId: '1:830688983522:ios:59dab948d541cb7c4121bb',
    messagingSenderId: '830688983522',
    projectId: 'smart-campus-d063f',
    storageBucket: 'smart-campus-d063f.firebasestorage.app',
    iosBundleId: 'com.example.smartCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAB-Mcf4yuaIzEZovjuTZ4HzKe4sAgnSY',
    appId: '1:830688983522:ios:59dab948d541cb7c4121bb',
    messagingSenderId: '830688983522',
    projectId: 'smart-campus-d063f',
    storageBucket: 'smart-campus-d063f.firebasestorage.app',
    iosBundleId: 'com.example.smartCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAB-Mcf4yuaIzEZovjuTZ4HzKe4sAgnSY',
    appId: '1:830688983522:web:59dab948d541cb7c4121bb',
    messagingSenderId: '830688983522',
    projectId: 'smart-campus-d063f',
    authDomain: 'smart-campus-d063f.firebaseapp.com',
    storageBucket: 'smart-campus-d063f.firebasestorage.app',
  );
} 